version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-us-east-1-code-bucket  --output-template-file outputTemplate.yaml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - template.yaml
    - outputTemplate.yaml