AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'aws-sam-s3-bucket-trigger-api

  When a file is saved to bucket A, a lambda function moves a copy of the file to
  bucket B, ideally through an API, and saving a record of the results of the lambda
  function

  '
Parameters:
  EnvType:
    Description: Environment type.
    Default: dev
    Type: String
    AllowedValues:
    - prod
    - dev
    - demo
    ConstraintDescription: must specify prod, dev, or demo.
Conditions:
  TestBucketName:
    Type: String
    Default:
      Fn::Sub: s3-bucket-trigger-api-test-bucket-${EnvType}
  WorkflowBucketName:
    Type: String
    Default:
      Fn::Sub: s3-bucket-trigger-api-workflow-bucket-${EnvType}
  TableName:
    Type: String
    Default:
      Fn::Sub: s3-bucket-trigger-api-log-table-${EnvType}
  SNSTopicName:
    Type: String
    Default:
      Fn::Sub: s3-bucket-trigger-api-sns-topic-${EnvType}
Globals:
  Function:
    Timeout: 60
Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: TestBucketName
      NotificationConfiguration:
        LambdaConfigurations:
        - Function:
            Fn::GetAtt:
            - WorkflowMainFunction
            - Arn
          Event: s3:ObjectCreated:*
    DependsOn:
    - WorkflowMainFunctionBucketEvent1Permission
  WorkflowBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: WorkflowBucketName
  S3Object:
    Type: AWS::S3::Object
    Properties:
      Target:
        Bucket:
          Ref: WorkflowBucket
        Key: README.md
        ContentType: text/markdown
      Body:
        Fn::Sub: '###

          # =================================================================

          # Main Workflow Enabled or disabled

          # =================================================================

          # Enabled: 0 for disabled, 1 for enabled

          enabled: 1

          '
  WorkflowMainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: s3-bucket-trigger-api-workflow-main-function-${EnvType}
      CodeUri: WorkflowMainFunction
      Handler: workflow_main_function.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          ENV_TYPE:
            Ref: EnvType
          TABLE_NAME:
            Ref: TableName
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: TestBucket
            Events:
            - s3:ObjectCreated:*
      Policies:
      - S3CrudPolicy:
          BucketName:
            Ref: TestBucketName
      - S3CrudPolicy:
          BucketName:
            Ref: WorkflowBucketName
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      - SNSPublishMessagePolicy:
          TopicName:
            Ref: SNSTopicName
